### ISSUE TITLE
Are animation frames and names included?

### ISSUE THREAD

**Issue by seivan** [danprince/aseprite-typescript-sprites#1]
Also great work! Anything that adds more to static typing is great!

**Comment by danprince** [comment]
Hey @seivan 👋. Not really, I'm afraid. This tool is just for spritesheets with many sprite slices in a frame (basically if you want to go straight to having an atlas, rather than working in lots of separate Aseprite files).

I could see the utility in a version of this tool that handled animations too, but the way it works would have to change enough that it would justify being a fork rather than an upgrade.

On the rare occasion that I use animations, I tend to draw each frame separately within the same animation frame of the Aseprite document. Each gets a slice and a name, then I switch frame by name. Only really works for very simple animations though.

<img width="785" alt="image" src="https://github.com/danprince/aseprite-typescript-sprites/assets/1266011/775fc29e-353e-4bad-81d1-dcdabba45a9a">
